import Head from 'next/head'
import Image from 'next/image'
import { Inter, Poppins, Roboto } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>

      {/* Ini Tabbing */}
      <Head>
        <title>Raincember.
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className='bg-gray-800 mx-32 pb-4'>
        {/*Ini Header  */}
        <div className='flex justify-center items-center'>
          <ul className='flex space-x-4 px-6 py-2 text-white bg-gray-500 rounded-full mt-5'>
            <li className='cursor-pointer hover:text-green-500'>About</li>
            <li className='cursor-pointer hover:text-green-500'>Articles</li>
            <li className='cursor-pointer hover:text-green-500'>Projects</li>
            <li className='cursor-pointer hover:text-green-500'>Speaking</li>
            <li className='cursor-pointer hover:text-green-500'>Uses</li>
          </ul>
        </div>

        {/*Ini PPK  */}
        <div className='mx-24'>
          <div className='mt-24'>
            <img src='/favicon.ico' height={65} width={65} />
            <h1 className='mt-8 text-white text-4xl font-bold max-w-xl'>
              Software designer, founder, and amateur astronaut.
            </h1>
            <p className='mt-8 text-gray-400 max-w-2xl leading-7'>
              I'm Spencer, a software designer and entrepreneur based in New York City. I'm the founder and CEO of Planetaria, 
              where we develop technologies that empower regular people to explore space on their own terms.
            </p>
            <div className='flex space-x-6 my-8'>
              <div>
                <img src="/twitter.svg" />
              </div>
              <div>
                <img src="/twitter.svg" />
              </div>
              <div>
                <img src="/twitter.svg" />
              </div>
              <div>
                <img src="/twitter.svg" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
